# Generated by Django 4.2 on 2023-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='department',
        ),
        migrations.DeleteModel(
            name='Registeration',
        ),
        migrations.RemoveField(
            model_name='department',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='department',
            name='img',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
