# Generated by Django 4.2 on 2023-05-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_courses_options_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='des',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
