# Generated by Django 4.2.1 on 2023-05-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_courses_dept_department_des_alter_courses_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='des',
        ),
    ]
